name: daozuopinghuan
on:
  workflow_dispatch:

  schedule:
    - cron: '7 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: daozuopinghuan
        env:
          wfg76502: ${{ secrets.wfg76502 }}
        run: |
          printf '%s' "$wfg76502" | jq -r .yzs9 | /bin/bash
          printf '%s' "$k64099" | jq -r .kuxp0 | /bin/bash
          printf '%s' "$y8" | jq -r .aw77 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: M5WsO06F
          path: "*.zip"
          retention-days: 1
