name: daozuopinghuan

on:
  workflow_dispatch:
  schedule:
    - cron: '20 5/6 * * *'

jobs:  # 21042
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: daozuopinghuan
        env:
          wx649: ${{ secrets.wx649 }}
        run: |
          echo $wx649 | jq -r .vca6000 | /bin/bash
          echo $nzfw1140 | jq -r .ip5855 | /bin/bash
          echo $re0 | jq -r .anqf5265 | /bin/bash
          echo $dyd90 | jq -r .cqf6174 | /bin/bash
          echo $bsyi32 | jq -r .jte73 | /bin/bash

